# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu-12.04-x64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.network :forwarded_port, guest: 80, host: 8081
  config.vm.network :private_network, ip: "192.168.33.10"
  config.vm.synced_folder "..", "/share", create: true, owner: 'vagrant', group: 'vagrant', mount_options: ['dmode=777']

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "../provisioning/playbook.yml"
    ansible.inventory_path = "../provisioning/hosts"
  end
end
